### ISSUE TITLE
FFO技能软件只能设置365秒

### ISSUE THREAD

**Issue by tw007tw007** [ckeleshi/FxPresser#3]
你好，FFO软件技能释放间隔能否设置多一点？
现在时间间隔只能设365秒，我想让他设7200秒以上这样能自动吃双倍卡。

**Comment by ckeleshi** [comment]
你这个需求可以用其他很多种方法完成，这个软件真不适合😅。

**Comment by tw007tw007** [comment]
能留个联系方式吗，想有偿做几个脚本
